[package]
name = "i3-wk"
version = "0.1.0"
authors = ["Marco Schlumpp <marco.schlumpp@gmail.com>"]

[dependencies]
serde = "0.7.14"
serde_macros = "0.7.14"
serde_json = "0.7.4"

[profile.release]
opt-level = 3
lto = true
