[package]
name = "i3-wk"
version = "0.1.0"
authors = ["Marco Schlumpp <marco.schlumpp@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
